### ISSUE TITLE
Setting config to nil produces cryptic error message

### ISSUE THREAD

**Issue by marckohlbrugge** [producthunt/ShareMeowClient#2]
When setting the config variables to nil you'll receive the following error when calling `.image_url`:

```
!! #<TypeError: no implicit conversion of nil into String>
```

I ran into this problem, because I'm using ENV variables in my initializer and accidentally forgot to set a value. This results in the ShareMeow config variables being set no nil, overriding the defaults and `.image_url` producing the cryptic error above.

Fortunately there's a limited codebase here so debugging this is rather painless, but I still think a more descriptive error message when calling `.image_url` or using nil as a configuration value would be handy.

**Comment by mscoutermarsh** [comment]
:+1: great idea. If you'd like to do a PR for this let me know. Otherwise I'll make this change when I get a chance. :smiley:
